<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_programatico extends CI_Model {

    function __construct() {
        parent::__construct();
        $this->load->database();
    }

    function lst_programatico_horario($p){
        
        /*$query = $this->db->query("SELECT H.DIASEMANA, H.HORAINICIAL, H.HORAFINAL, T.CODTURMA, D.NOME FROM RM.SHORARIO H
        JOIN RM.SHORARIOTURMA HT ON HT.CODHOR = H.CODHOR
        JOIN RM.STURMADISC T ON HT.IDTURMADISC = T.IDTURMADISC
        JOIN RM.SDISCIPLINA D ON D.CODDISC = T.CODDISC
        JOIN RM.SMATRICPL M ON M.CODTURMA = T.CODTURMA AND M.CODSTATUS = 15
        WHERE M.RA = '".$p['p_ra']."' ORDER BY HORAINICIAL ASC");*/
        $query = $this->db->query("SELECT H.DIASEMANA, H.HORAINICIAL, H.HORAFINAL, T.CODTURMA, D.NOME, CONTEUDO FROM RM.SHORARIO H
        JOIN RM.SHORARIOTURMA HT ON HT.CODHOR = H.CODHOR
        JOIN RM.STURMADISC T ON HT.IDTURMADISC = T.IDTURMADISC
        JOIN RM.SETAPAS ET ON ET.IDTURMADISC = T.IDTURMADISC 
        JOIN RM.SPROVASCOMPL PC ON T.IDTURMADISC = PC.IDTURMADISC AND CONTEUDO IS NOT NULL AND PC.CODETAPA = ET.CODETAPA
        JOIN RM.SDISCIPLINA D ON D.CODDISC = T.CODDISC
        JOIN RM.SMATRICPL M ON M.CODTURMA = T.CODTURMA AND M.CODSTATUS = 15
        WHERE M.RA = '".$p['p_ra']."' ORDER BY HORAINICIAL ASC");
        return $query->result_array();

    }
   


    function lst_conteudo_programatico($p){
        $query = $this->db->query("SELECT SMAT.RA ,H.DIASEMANA, 
        CASE 
             WHEN H.DIASEMANA = '2' THEN 'SEGUNDA-FEIRA'
             WHEN H.DIASEMANA = '3' THEN 'TERÇA-FEIRA'
             WHEN H.DIASEMANA = '4' THEN 'QUARTA-FEIRA'
             WHEN H.DIASEMANA = '5' THEN 'QUINTA-FEIRA'
             WHEN H.DIASEMANA = '6' THEN 'SEXTA-FEIRA'
        END AS DIA, 
        T.NOME AS CURSO, TD.CODTURMA, NVL(D.COMPLEMENTO,D.NOME) AS DISCIPLINA, 
        DBMS_LOB.SUBSTR(SP.CONTEUDO, 4000, 1 ) as CONTEUDO, DBMS_LOB.SUBSTR(SP.CONTEUDOEFETIVO, 4000, 1) AS CONTEUDOEFETIVO, SP.DATA, H.HORAINICIAL, 
        H.HORAFINAL, SP.DATAEFETIVA FROM RM.SPLANOAULA SP
        JOIN RM.STURMADISC TD ON TD.IDTURMADISC = SP.IDTURMADISC AND TD.CODCOLIGADA = SP.CODCOLIGADA
        JOIN RM.SHORARIOTURMA HT ON HT.IDTURMADISC = TD.IDTURMADISC AND HT.IDHORARIOTURMA = SP.IDHORARIOTURMA AND HT.CODHOR = SP.CODHOR
        JOIN RM.SHORARIO H ON H.CODHOR = HT.CODHOR AND H.CODCOLIGADA = TD.CODCOLIGADA
        JOIN RM.STURNO T ON T.CODTURNO = H.CODTURNO AND T.CODCOLIGADA = H.CODCOLIGADA
        JOIN RM.SDISCIPLINA D ON D.CODDISC = TD.CODDISC AND D.CODCOLIGADA = T.CODCOLIGADA
        JOIN RM.SMATRICPL SMAT ON SMAT.CODTURMA = TD.CODTURMA AND TD.IDPERLET = SMAT.IDPERLET AND SMAT.CODCOLIGADA = D.CODCOLIGADA
        JOIN RM.SPLETIVO SANO ON SANO.IDPERLET = SMAT.IDPERLET AND SANO.CODCOLIGADA = SMAT.CODCOLIGADA AND SANO.CODPERLET = TO_CHAR(SYSDATE,'YYYY') 
        WHERE SP.DATA = TO_DATE('".$p['p_data']."','DD/MM/YYYY') --LISTA INFO REFERENTE A DATA ATUAL
        --AND SP.CONTEUDOEFETIVO IS NOT NULL --LISTA CONTEúDO QUE FOI PREENCHIDO
        AND SP.CODCOLIGADA = 1 
        AND SMAT.CODSTATUS = 15 
        AND SMAT.RA = '".$p['p_ra']."' ORDER BY H.HORAINICIAL, H.HORAFINAL ASC"); //and h.diasemana = 2
        
        return $query->result_array();
    }

}



